import ProvidersWrapper from './ProvidersWrapper';
import Navbar from './components/Navbar';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body 
    //   className="bg-scroll" style={{
    // backgroundImage: "url('./public/bg-img.jpg')",
    //  height: "972px",
    // }}
    >
        <ProvidersWrapper>
          {/* <Navbar /> */}
          {children}
        </ProvidersWrapper>
      </body>
    </html>
  );
}
